### ISSUE TITLE
irreversible elementary step

### ISSUE THREAD

**Issue by tuhinsk** [SUNCAT-Center/catmap#103]
How can an irreversible elementary step be added in the mkm file? 
I know that certain reaction do not happen on pure transition metals at low temperature but CatMAP do not capture it correctly, how I can direct CatMAP to products observed in experimentally?

**Comment by ajmedford** [comment]
The way CatMAP sets up reactions it essentially assumes that everything is "reversible" due to the principle of [microscopic reversibility](https://en.wikipedia.org/wiki/Microscopic_reversibility). Of course in practice some things are effectively irreversible, but this is due to an impractically large reverse barrier (compared to the forward barrier). If your final state is significantly (probably >1 eV) more thermodynamically stable than your initial state then CatMAP will treat the reaction as practically irreversible.
