### ISSUE TITLE
Use descriptor via "dummy" site does not work

### ISSUE THREAD

**Issue by lixinyuu** [SUNCAT-Center/catmap#118]
Hi,

When I tried to use a O_s as descriptor for Ethylene Glycol decomposition, CatMap give a error message as
 "AttributeError: Descriptor O_s does not appear in reaction network. Add descriptor to network via "dummy" site, or use an adsorbate from the network as a descriptor."
However, even if I add the O_s as a dummpy site by add rxn expression " O* -> O*", the model end with "mapper_iteration_2: fail - no solution at 225 points."
This error can be regenerated in the CO oxidation model of Tutorial 2 by adding the following line to energies.txt.
```
Ru	111	C	1.3	fcc	[]	[]	test
Rh	111	C	1.34	fcc	[]	[]	test
Pd	111	C	1.55	fcc	[]	[]	test
Ni	111	C	1.63	fcc	[]	[]	test
Pt	111	C	1.7	fcc	[]	[]	test
Cu	111	C	2.58	fcc	[]	[]	test
Ag	111	C	2.99	fcc	[]	[]	test
Au	111	C	3.04	fcc	[]	[]	test
```
add chagne line 13 to 21 into 
```               
              'CO* +  O* <-> O-CO* + * -> CO2_g + 2*',
               'C* -> C*'

                   ]


surface_names = ['Pt', 'Ag', 'Cu','Rh','Pd','Au','Ru','Ni'] #surfaces to include in scaling (need to have descriptors defined for each)

descriptor_names= ['O_s','C_s'] #descriptor names

descriptor_ranges = [[-1,3],[-0.5,4]]
```
Is this a bug or my understanding of "dummy" site is wrong?

Thanks.

**Comment by gusmaogabriels** [comment]
@lixinyuu ,

I have just tried to reproduce your error by including the changes you propose.  However, I am not sure what exactly you intend to do with this setup. Can you explain in more details what you want to obtain?

 As for "dummy" site, are you actually referring to a dummy species to use as reference or are you trying to use adsorbed carbon (`C_s`)as binding energy descriptor? In the latter case, you will need to provide `C_s`'s actual binding energy for each surface (in your example, you copied over those from `CO_s`) and have elementary reactions that connect `C_s` to the chemical reaction; otherwise, CatMAP will provide initial coverage estimates for each adsorbate species and `C_s` will become "trapped" into its initial coverage.

I hope this helps,

**Comment by ajmedford** [comment]
In this case a "dummy" site refers to a new site type that does not compete with others. For example:

O2 + 2*_d -> 2O_d

where *_d is a site with no other competing adsorbates. The strategy you have employed will add a differential equation to the system that makes it impossible to solve, hence the failure to converge.
