### ISSUE TITLE
'strerror' while perofmring Degree of rate of control analysis

### ISSUE THREAD

**Issue by malik-ust** [SUNCAT-Center/catmap#132]
![image](https://user-images.githubusercontent.com/71395030/103861103-3373a980-5100-11eb-9a09-a9ac8112bed0.png)
![catmap](https://user-images.githubusercontent.com/71395030/103861137-44bcb600-5100-11eb-928b-0b2923212d98.JPG)
  

Hi; This is Malik.
well, I am working on the NOx reduction reaction system. While performing the DRC analysis by using catmap. I am facing some error " NameError: name 'strerror' is not defined " please anyone can help me out how to fix that. For my system, the rest of the plots are generated very well. I mean production rate coverage etc.  I am just facing some problem for DRC analysis part. Please suggest some solution to overcome this issue.  Thanks
Regards;

Malik Waqar
Graduate Student

**Comment by ajmedford** [comment]
It appears that this is an issue with error handling, possibly due to syntax changes in Python 3 (or possibly just a latent bug). This StackOverflow post contains some fixes, though I don't currently have time to implement, test, and submit the pull request.

https://stackoverflow.com/questions/4097461/printing-out-actual-error-message-for-valueerror

**Comment by gusmaogabriels** [comment]
This seems like a quick fix. I am working on it and will push a new commit soon.
It might be desirable to add DRC to the continuous integration workflow.

**Comment by gusmaogabriels** [comment]
The problem has been fixed in #134
